### PR TITLE
Feature/update profile

### PR DESCRIPTION
**Pull request by toyyibat1**
update user view profile

### CODE REVIEW

**Comment by Blazebrain** [comment]
@isaacadariku Can you help her swap the base to dev?

**Review by Quwaysim — CHANGES_REQUESTED** [review]
- target dev, not master
- add your .vscode and .fvm dirs to gitignore
- also changes made in 108 files? Your PR says "update user view profile" Please pull before you do your work (make sure your work branch is even with our Dev branch before you start working on your local branch)

**Comment by toyyibat1** [comment]
changes have been made

**Review by toyyibat1 — COMMENTED** [review]
resolve changes

**Comment by toyyibat1** [comment]
changes have been done

**Review by Quwaysim — APPROVED** [review]

**Review by mariamadebolahamzat — APPROVED** [review]
Good

**Pull request merged**
