### PR TITLE
Add People To Channel

### PR DESCRIPTION
**Pull request by eunicePops**
Adding People to Channel

### CODE REVIEW

**Comment by eunicePops** [comment]
Loading a list of People in an organization already working, adding the people to the channel has already been implemented but seems there is an issue with backend
https://user-images.githubusercontent.com/40694423/134806151-82100c0b-7a41-4bde-aeee-1935d6ca6242.MP4

**Comment by Blazebrain** [comment]
Nice work

Pull and fix conflicts 

The reason it's throws that error is because only a member with admin access (meaning the person who created the channel) can add people

**Comment by eunicePops** [comment]
Thank you.
Please has created channel been integrated

**Comment by eunicePops** [comment]
I mean create channel

**Comment by Blazebrain** [comment]
Fix Conflicts

**Comment by YenumJay** [comment]
Pull latest changes from dev and resolve conflicts.

**Comment by pauleke65** [comment]
@eunicePops You opened another PR for the same issue, so I a closing this

**Pull request closed without merging**
