### PR TITLE
Add native launch screen

### PR DESCRIPTION
**Pull request by usmanabdulmajid**
Link to issue: #567

https://user-images.githubusercontent.com/63570223/132050472-52727873-adf8-4fa3-b148-90b7978a2cf5.mp4

### CODE REVIEW

**Review by Quwaysim — APPROVED** [review]
legit

**Review by Quwaysim — DISMISSED** [review]
legit

**Comment by Tamunorth** [comment]
This also closes issue #1

**Review by mayor04 — APPROVED** [review]
All good

**Review by mayor04 — APPROVED** [review]
Okayyy

**Review by Blazebrain — APPROVED** [review]

**Pull request merged**
