### PR TITLE
Created of bottom navigation menu in alignment with the stacked architecture in flutter

### PR DESCRIPTION
**Pull request by mayor04**

### CODE REVIEW

**Review by Blazebrain — DISMISSED** [review]

**Review by Quwaysim — APPROVED** [review]

**Review by Quwaysim — APPROVED** [review]
conflicts to be fixed

**Review by Quwaysim — APPROVED** [review]
approved

**Review by Blazebrain — APPROVED** [review]
Blazing all the way, all

**Review by Blazebrain — APPROVED** [review]
Blazing all the way, all

**Pull request merged**
