### PR TITLE
Changed the textfields focus color to zuriPrimary Color

### PR DESCRIPTION
**Pull request by DestinyOgbonna**
https://user-images.githubusercontent.com/80477923/139533484-25009f8f-6299-4d6c-b64c-4158c2d8e92b.mp4

### CODE REVIEW

**Review by pauleke65 — CHANGES_REQUESTED** [review]
Great Work, but it seems not everything was changed, the label and cursor color is still blue.
also try changing ```primaryColor``` to ```primarySwatch``` and just play with it a bit to see how everything turns out.
Also refer to [this](https://api.flutter.dev/flutter/material/ThemeData-class.html) for more info🙏🏽.

**Comment by DestinyOgbonna** [comment]
https://user-images.githubusercontent.com/80477923/139921774-608fa0ad-a9fc-4bc6-aaf4-b45fe1e2bf2e.mp4

Changes made

**Review by pauleke65 — APPROVED** [review]
Awesome

**Review by jeremiahseun — APPROVED** [review]
LGTM

**Pull request merged**
