### PR TITLE
Added thread card widget for shared messages and UI fixes

### PR DESCRIPTION
**Pull request by Nathaniel-Akubuo**
https://user-images.githubusercontent.com/61379839/137622748-6323dcd5-7a29-43b9-ab8f-0651ce9cf715.mp4

### CODE REVIEW

**Review by jeremiahseun — APPROVED** [review]
LGTM

**Review by jeremiahseun — CHANGES_REQUESTED** [review]
Please make the appbar white background
You can set whiteBackground: true in the appbar and fix conflicts.

**Review by pauleke65 — CHANGES_REQUESTED** [review]
No need to create a new thread card, just pass it as a PostQuotedReply

**Comment by pauleke65** [comment]
Hi @Nathaniel-Akubuo, if you're still on this please make a commit by 3PM before it's closed🙏🏾.

**Comment by pauleke65** [comment]
Closed due to inactivity and response from author

**Pull request closed without merging**
