### PR TITLE
fixed the #373 issue

### PR DESCRIPTION
**Pull request by Cdf-creator**
User should be able to clear his/her status (#373)

Link to testing: https://appetize.io/app/zw20zmx264azfew3a6t69x91r8?device=iphone6s&scale=75&orientation=portrait&osVersion=13.7

Procedures for Testing:

* Run the application
* Click the green floating action button at the bottom right to navigate to the testing page.
* You will be taking to a page that asks you to exact time you want your status to clear. 
* The arrow back icon will take you back to the previous page.

This verifies that the user can clear their status for an exact length of time that they want.

### CODE REVIEW

**Comment by mayor04** [comment]
You have a wrong description with no appetize link and video gif please update it

**Comment by Cdf-creator** [comment]
> You have a wrong description with no appetize link and video gif please update it

**Comment by Cdf-creator** [comment]
> You have a wrong description with no appetize link and video gif please update it

I will add the appetize link and gif in a moment. how should the description look like?

**Comment by mayor04** [comment]
- Pull from upstream
- solve all the conflict
- push to origin (do not create another pull request)
- It will automatically appear here

**Review by mayor04 — APPROVED** [review]

**Review by cuddle-bunny — APPROVED** [review]

**Pull request merged**
