### PR TITLE
feat: Channel Threads(Add and receive replies)

### PR DESCRIPTION
**Pull request by Blazebrain**
This feature does the following:
- Allows a user receive replies sent to any message in the channel
- Send a reply to a particular message in channel
- Performing both of these operations in real time

To test:
- Launch the app
- Click on any organization
- Select any channel of choice
- Click on any of the previously sent messages
- Checkout replies sent to messages
- Add a reply to any of the messages and watch it added to the list in real time
- Log out of the organization and login in again
- Click the channel and message you sent a reply to; the reply would be part of the replies listed out.
 Demo gif

### CODE REVIEW

**Review by YenumJay — APPROVED** [review]
LGTM

**Comment by Blazebrain** [comment]
> All good, just resolve conflicts and we are good

All conflicts fixed

**Review by YenumJay — APPROVED** [review]
LGTM

**Review by pauleke65 — APPROVED** [review]
LG

**Pull request merged**
