### PR TITLE
Project-wide string extraction - 1/3

### PR DESCRIPTION
**Pull request by Quwaysim**
Project-wide string extraction to lib/constants/app_strings.dart

### CODE REVIEW

**Comment by Quwaysim** [comment]
Made this pull request because conflicts are getting harder to resolve. zc:dev branch commits moving faster than my pace

**Review by pauleke65 — DISMISSED** [review]
LGTM

**Review by jeremiahseun — DISMISSED** [review]
Awesome! 
LGTM

**Comment by jeremiahseun** [comment]
There are conflicts o.
Please resolve conflicts

**Comment by Quwaysim** [comment]
@jeremiahseun, the conflicts popped-up because a merge with the same files I worked on was done before you merged my PR. This will happen almost everytime until my PR is reviewed and merged.

**Comment by Quwaysim** [comment]
Conflicts resolved @pauleke65 @YenumJay @jeremiahseun

**Review by pauleke65 — APPROVED** [review]

**Review by jeremiahseun — COMMENTED** [review]
Awesome

**Review by jeremiahseun — APPROVED** [review]

**Pull request merged**
