### PR TITLE
Add Loader To Edit Profile Save Button

### PR DESCRIPTION
**Pull request by ugoostanleyibe**
This update adds a loader (CircularProgressIndicator) to the 'Save' button in the EditProfileView as can be seen below:

demo7

There is also the General Search feature which is a work in progress and whose purpose is to enable a user search through all the messages and files in the channels they have joined. The demo can be seen below:

demo6

### CODE REVIEW

**Comment by jeremiahseun** [comment]
Please show a video of what you have implemented.

**Review by jeremiahseun — DISMISSED** [review]
LGTM

**Review by pauleke65 — CHANGES_REQUESTED** [review]
PR is doing too many things, please let it more be specific 🙏🏾.

**Comment by ugoostanleyibe** [comment]
> PR is doing too many things, please let it more be specific 🙏🏾.

Omo... me sef don tire 😵

**Comment by pauleke65** [comment]
@ugoostanleyibe Please make a separate PR for each task done here.

**Comment by pauleke65** [comment]
@ugoostanleyibe Please make a separate PR for each task done here.

**Pull request closed without merging**
