### PR TITLE
Unit tests for Local storage, User services, Navigation Service, SnackBar Service, Bottom Sheet and Dialog Service.

### PR DESCRIPTION
**Pull request by Xclusivecyborg**
Wrote unit tests for Local storage, User services, Snack bar service, Bottom sheet service, Dialog service, Navigation Service. 
test-Unit

### CODE REVIEW

**Review by YenumJay — CHANGES_REQUESTED** [review]
Please do a recording of your screen showing the tests running and the result you get.

**Comment by Xclusivecyborg** [comment]
> Please do a recording of your screen showing the tests running and the result you get.

Video has now been updated

**Review by pauleke65 — CHANGES_REQUESTED** [review]
Check the failed build check and fix the issues

**Review by pauleke65 — CHANGES_REQUESTED** [review]
Great job, please delete unused codes

**Review by YenumJay — APPROVED** [review]
LG

**Review by pauleke65 — APPROVED** [review]
LG

**Pull request merged**
