### PR TITLE
fixes #50 - toggle dark mode

### LINKED ISSUE #50: Toggle Dark Mode
As a user, I want to have an option to enable a dark mode/theme so that I can easily read texts at night.

### PR DESCRIPTION
**Pull request by Obikwelu**
Toggle dark mode fixes #50

https://user-images.githubusercontent.com/31783214/132082442-c37f1201-c3c0-4669-80e4-668133fd1bf6.mp4

Appetize link
https://appetize.io/app/fz7zm351b2f3rwbp51034tda5w?device=nexus5&scale=75&orientation=portrait&osVersion=8.1

### CODE REVIEW

**Comment by Quwaysim** [comment]
ThemeServices already implemented this

**Comment by mayor04** [comment]
Post the link to your appetize app

**Comment by Obikwelu** [comment]
> Post the link to your appetize app

**Comment by Obikwelu** [comment]
Quwaysim said the theme has been implemented already.

**Comment by Obikwelu** [comment]
> Post the link to your appetize app

Coming up soon

**Comment by Obikwelu** [comment]
> Post the link to your appetize app

https://appetize.io/app/fz7zm351b2f3rwbp51034tda5w?device=nexus5&scale=75&orientation=portrait&osVersion=8.1

**Pull request closed without merging**
