### PR TITLE
Theme Fixes 1/2

### PR DESCRIPTION
**Pull request by Quwaysim**
- App-Wide Dark Mode Implementation

theme 1

### CODE REVIEW

**Comment by Quwaysim** [comment]
many files changed due to the removal static color values assigned to widgets

**Comment by pauleke65** [comment]
Boss, please upload video 🤲🏽

**Review by pauleke65 — CHANGES_REQUESTED** [review]
More info req

**Review by pauleke65 — DISMISSED** [review]

**Review by pauleke65 — APPROVED** [review]
LG

**Review by jeremiahseun — APPROVED** [review]
LGTM

**Pull request merged**
