### PR TITLE
pinned messages

### PR DESCRIPTION
**Pull request by Asukwo-comfort**
#677  - Pinned Messages on a separate tab

https://appetize.io/app/u9vcuztb2f9nnnq7anb3h5ck54

https://user-images.githubusercontent.com/64699982/132122433-0c731be4-fab6-40cb-bd71-5cb35493a098.mp4

Issue solved: pinned messages on a separate tab

### CODE REVIEW

**Comment by Quwaysim** [comment]
test link and screenrecord

**Review by Quwaysim — CHANGES_REQUESTED** [review]
please provide test link and screenrecord

**Comment by mayor04** [comment]
Your commit should include

-  Screen record of what you did
- An appetize link to test what you did 
- And the issue you are solving 

Without these we cant know if what you wrote is right

**Comment by Quwaysim** [comment]
@Asukwo-comfort your project structure I'd not consistent with zurichat's dev branch structure. Also, you didn't implement stacked

**Review by Quwaysim — APPROVED** [review]

**Review by mayor04 — APPROVED** [review]

**Pull request merged**
