### PR TITLE
Workflow: Forgot Password

### PR DESCRIPTION
**Pull request by Detective-Khalifah**
Milestone 1 & 2 of the forgot password workflow achieved.

Workflow:
[/] Open Application
[/] Navigate to forgot password view from the sign in view
[/] Enter registered e-mail
[/] Receive & Enter OTP
[/] Enter and confirm new password.
[/] Navigate to sign in. And sign in with new password

Integration Operational.

Devs: @DestinyOgbonna & @Detective-Khalifah
Testing link : https://appetize.io/app/aux95zc70e0ymvp9nag4ncw4km?device=pixel4xl&scale=50&orientation=portrait&osVersion=10.0

### CODE REVIEW

**Comment by Blazebrain** [comment]
Fix Conflicts

**Comment by Detective-Khalifah** [comment]
app.router was the trickiest... Wish it'll be ousted ha ha

**Comment by Quwaysim** [comment]
> _app.router_ was the trickiest... Wish it'll be ousted ha ha

No sir, it's doing a great job, it'll not be ousted 😂

**Comment by Detective-Khalifah** [comment]
> > _app.router_ was the trickiest... Wish it'll be ousted ha ha
> 
> No sir, it's doing a great job, it'll not be ousted 😂
> 
> I hope you did not edit it manually? it's better to use the generator

Manual editing is a little unwise

**Review by Blazebrain — APPROVED** [review]

**Review by Quwaysim — APPROVED** [review]

**Comment by Detective-Khalifah** [comment]
I see it's been merged already. Here' the belated video. Hope you like it

https://user-images.githubusercontent.com/58272349/134813442-c01597fa-1d97-4675-9a71-2ba229f2595c.mp4

:

**Pull request merged**
