### PR TITLE
Addition of onboarding screen to app -- resolves issues #63 & #443

### PR DESCRIPTION
**Pull request by Detective-Khalifah**
- [/] Onboarding screens display what the app is about -- solves issue #63 
- [/] Dot indicators tell how many pages there are on the onboarding screen -- solves #443 

https://user-images.githubusercontent.com/58272349/132072186-bf7a6c1a-33d5-4170-b00b-2d550147fdc6.mp4

>[Testing link](https://appetize.io/app/dbn0t008afbx0xc61bttw1wctr)

### CODE REVIEW

**Review by Quwaysim — CHANGES_REQUESTED** [review]
implement stacked (use viemodel), fix conflicts

**Comment by Detective-Khalifah** [comment]
> implement stacked (use viemodel), fix conflicts

Conflicts merged; implementing stack. Will be done in 30 minutes, less or so.

**Comment by Detective-Khalifah** [comment]
Evening, @Quwaysim 
- [ ] Merging done.
- [ ] Code refactored to implement the Stacked architectural pattern

Check out my code and merge the Pull Request #586, if you would please. Thank you!

**Review by Quwaysim — APPROVED** [review]

**Review by mayor04 — APPROVED** [review]
All good

**Pull request merged**
