### PR TITLE
Stacked architecture setup

### PR DESCRIPTION
**Pull request by Nathaniel-Akubuo**
This PR resolves issue #526

### CODE REVIEW

**Comment by isaacadariku** [comment]
LGTM

**Review by Blazebrain — APPROVED** [review]
Good to go.

**Review by Blazebrain — COMMENTED** [review]
Well done.

**Review by Blazebrain — APPROVED** [review]

**Review by Blazebrain — APPROVED** [review]

**Review by Quwaysim — APPROVED** [review]
All good

**Review by Quwaysim — APPROVED** [review]

**Review by Blazebrain — APPROVED** [review]
It's good to go

**Review by Quwaysim — APPROVED** [review]
All good

**Comment by markessien** [comment]
No testing link

**Pull request merged**
