### PR TITLE
Added launcher icon resolves #537

### LINKED ISSUE #537: Unique application icon
As a user I'd like to see a unique icon for the application so I can easily differentiate the application from other apps.

### PR DESCRIPTION
**Pull request by bountyforager**
I changed the app's icon from flutter's default icon to Zuri's

resolves #537

https://appetize.io/app/jk3cr8htjnzfw79vjvxbuekk18?device=nexus5&scale=75&orientation=portrait&osVersion=8.1

Screenshot (123)

### CODE REVIEW

**Comment by Quwaysim** [comment]
Job well done but you didn't link the issue and the appetize link, please do so

**Comment by bountyforager** [comment]
resolves #537

> Job well done but you didn't link the issue and the appetize link, please do so

I have done that now. Thank you

**Review by Quwaysim — APPROVED** [review]
looks good

**Comment by Quwaysim** [comment]
why did you close the pr?

**Review by Blazebrain — DISMISSED** [review]
Let's go

**Pull request closed without merging**
