### PR TITLE
Implementation of get and store all the users in an organization

### PR DESCRIPTION
**Pull request by abdussamadbsg**

### CODE REVIEW

**Review by pauleke65 — CHANGES_REQUESTED** [review]
Run ```flutter analyze``` and fix all issues
show a video demo of the work done

**Review by pauleke65 — CHANGES_REQUESTED** [review]
Run ```flutter analyze``` and fix all issues
show a video demo of the work done

**Review by pauleke65 — APPROVED** [review]

**Review by jeremiahseun — APPROVED** [review]
LGTM

**Review by pauleke65 — APPROVED** [review]
LG

**Pull request merged**
