### PR TITLE
Channel Message Error Checking

### PR DESCRIPTION
**Pull request by Lord-Chris**
First video shows a preview of the errors along with the log in process

https://user-images.githubusercontent.com/58702861/135666585-d57d45da-8bde-4e58-8236-ac52ad928d8d.mp4

Second Video shows it working without the log in process

https://user-images.githubusercontent.com/58702861/135669128-541c286e-1df3-412f-9196-346f2688fadd.mp4

### CODE REVIEW

**Comment by pauleke65** [comment]
@Lord-Chris Please replace video with one showing you turning off and then on your internet, and the connection status changing appropriately.

**Review by YenumJay — CHANGES_REQUESTED** [review]
The video preview needs to show how the error comes up when the internet is shut from your device. Currently, error comes up even if there is network on your device.

**Comment by Lord-Chris** [comment]
@pauleke65 @YenumJay video has been added, bluetooth tethering was my source of internet

**Review by jeremiahseun — APPROVED** [review]
LGTM

**Review by YenumJay — APPROVED** [review]
LGTM

**Pull request merged**
