### PR TITLE
Setup Local storage service

### PR DESCRIPTION
**Pull request by Blazebrain**
This PR solves issue #535 

It allows a user to persist data between app restarts. 

Instead of direct implementation of the shared preferences package, the service approach is used,reducing the dependence on the package. Therefore, in the nearest future, if the preferred choice for local Storage changes from SharedPreferences to SQLite, Hive or any database, the full app remains undisturbed and the changes can be easily implemented.

Here is a link to the live app for testing

https://appetize.io/app/01maqa9k0b50p27nvh22dca3d0

To navigate to the testing page, kindly click the Green Floating Action button on the bottom right side.

After entering your details, to verify the data is saved, kindly click the button to go back to the screen and verify the data. If installed on a real device or emulator, you can restart the app and check the persisted data.

The code for the testing page and also the test methods would be removed once the service has been tested and approved.

### CODE REVIEW

**Comment by markessien** [comment]
Screen is blank

**Comment by Blazebrain** [comment]
> Screen is blank

Can you please help check it again?

It shows the screen here

**Review by Quwaysim — DISMISSED** [review]
Tested... looks good.

**Review by Sasaleniyan — APPROVED** [review]
Code tested and reviewed.

- Blanked screen cited by @markessien in https://github.com/zurichat/zc_app/issues/536#issuecomment-910092234_  resolved.

**Review by Quwaysim — APPROVED** [review]

**Review by mayor04 — APPROVED** [review]
Approved

**Pull request merged**
