### PR TITLE
Create Add Workspace View

### PR DESCRIPTION
**Pull request by josh4500**
Link to issue: Issue #568

https://user-images.githubusercontent.com/61246632/132049547-9288641b-9019-42f2-9831-f739fda000ab.mp4

Launch app to test the page

https://github.com/zurichat/zc_app/issues/568

### CODE REVIEW

**Review by Quwaysim — CHANGES_REQUESTED** [review]
stacked not implemented... no viewmodel implementation found

**Comment by josh4500** [comment]
> stacked not implemented... no viewmodel implementation found

Wasn't sure if the viewmodel is to be created by me or someone else. All other contributors working on the workspace section have different task and I think the workspace viewmodel should be a task for another person.

**Comment by josh4500** [comment]
Fix missing ViewModel

**Comment by mayor04** [comment]
Post your appetize link here

**Comment by josh4500** [comment]
> Post your appetize link here
It was in the issue
https://appetize.io/app/953g3np66n6y0f5qmm7tqjy5tr

**Review by Quwaysim — APPROVED** [review]

**Review by Quwaysim — APPROVED** [review]

**Review by mayor04 — APPROVED** [review]

**Pull request merged**
