### PR TITLE
dmJumpToView UI adjustment made, ChannelInfo UI redesigned and Errors fixed

### PR DESCRIPTION
**Pull request by imfaith-hq**

### CODE REVIEW

**Comment by Blazebrain** [comment]
Fix the conflicts 

Also, crosscheck the other codes and ensure your code is not scattering others own

Well done boss

**Comment by imfaith-hq** [comment]
> Fix the conflicts 
> 
> 
> 
> Also, crosscheck the other codes and ensure your code is not scattering others own
> 
> 
> 
> Well done boss

Done

**Comment by YenumJay** [comment]
Pull latest changes from dev and resolve conflicts.

**Comment by pauleke65** [comment]
Awesome work, just resolve all the issues from flutter analyze and you'll be good to go

**Comment by imfaith-hq** [comment]
> Awesome work, just resolve all the issues from flutter analyze and you'll be good to go

done sir

**Comment by pauleke65** [comment]
@imfaith-hq  Please pull from the dev branch and resolve your conflicts

**Comment by imfaith-hq** [comment]
> @imfaith-hq  Please pull from the dev branch and resolve your conflicts

Pls who else is working on channelinfo page? I thought I signified so I'm surprised changes are being made on it repeatedly

**Comment by pauleke65** [comment]
> > @imfaith-hq  Please pull from the dev branch and resolve your conflicts
> 
> Pls who else is working on channelinfo page? I thought I signified so I'm surprised changes are being made on it repeatedly

I'm not aware of anyone else, but I'll keep an eye out.
For now fix the conflicts so that your PR can be merged

**Review by pauleke65 — APPROVED** [review]

**Comment by imfaith-hq** [comment]
> > > @imfaith-hq  Please pull from the dev branch and resolve your conflicts
> > 
> > 
> > Pls who else is working on channelinfo page? I thought I signified so I'm surprised changes are being made on it repeatedly
> 
> I'm not aware of anyone else, but I'll keep an eye out. For now fix the conflicts so that your PR can be merged

done sir

**Review by jeremiahseun — APPROVED** [review]
LGTM

**Pull request merged**
