### PR TITLE
Add People to Channel Conflict Resolved

### PR DESCRIPTION
**Pull request by eunicePops**

### CODE REVIEW

**Comment by YenumJay** [comment]
Pull latest changes from dev and resolve your conflicts.

**Comment by jeremiahseun** [comment]
Please fIx conflicts

**Comment by pauleke65** [comment]
@eunicePops Hi, please resolve the errors in your PR, remove the unused imports and use the right naming conventions where analyze specifies

**Review by pauleke65 — APPROVED** [review]
Looks Good

**Review by YenumJay — APPROVED** [review]
Looks good to me.

**Pull request merged**
