### PR TITLE
Fixed Remind me on Messages

### PR DESCRIPTION
**Pull request by HassanTeslim007**
Remind me dialog fixed

### CODE REVIEW

**Review by jeremiahseun — APPROVED** [review]
LGTM

**Review by jeremiahseun — CHANGES_REQUESTED** [review]
Please fix conflicts and update video

**Review by pauleke65 — CHANGES_REQUESTED** [review]
Please upload video showing working code

**Comment by pauleke65** [comment]
@HassanTeslim007 Your PR will by closed at 3PM WAT today, since there's been no response from you anywhere.
And there's also no video demonstrating your task🙏🏾.

**Comment by HassanTeslim007** [comment]
I'm sorry but my system is faulty at the moment. I'll make the required changes as soon as I get it fixed.

**Comment by pauleke65** [comment]
Reached the PR's author, will make a new one when ready.
Closing this

**Pull request closed without merging**
